#!/usr/bin/env python

import sys
import os

args = []
cmd = []
target = None
port = None

dual_opts = [
    '-b', '-B', '-c', '-D', '-E', '-e', '-F', '-I', '-i', '-J',
    '-L', '-l', '-m', '-O', '-o', '-Q', '-R', '-S', '-W', '-w'
]

marg = [] + sys.argv
scmd = marg.pop(0)
while marg:
    v = marg.pop(0)
    if target is not None:
        cmd.append(v)
    elif v == "-p":
        if marg:
            port = marg.pop(0)
    elif v in dual_opts:
        args.append(v)
        if marg:
            args.append(marg.pop(0))
    elif v[0] == "-":
        args.append(v)
    else:
        target = v

if target is None:
    print("Wrong keys. Usage: %s [<options>] [user@]host[:port] [<command>]" % scmd)
    sys.exit(1)

if target.find(":") > -1:
    tokens = target.split(":")
    if len(tokens[1].strip()) > 0:
        port = tokens[1].strip()
        target = tokens[0]
    else:
        print("Wrong keys. Usage: %s [<options>] [user@]host[:port] [<command>]" % scmd)

if port is not None:
    args = args + ['-p', port]

os.execvp("ssh", ["ssh"] + args + [target] + cmd)
