#!/bin/bash
fname="$0"
if [ -f "$fname" ] ; then
    basedir="$(dirname $0)"
elif [ -f "$(which $0)" ] ; then
    basedir="$(dirname $(realpath $(which $0)))"
else
    echo "Couldn't find basedir" 1>&2
    exit 1
fi
which podman > /dev/null && builder=podman
which container > /dev/null && builder=container
which docker > /dev/null && builder=docker

[ "$builder" = "" ] && { echo "None of pdoman, container or docker tool found, aborting" ; exit 1 ; }

$DEBUG $builder build -t go-builder-$1:latest -f Containerfile.$1
