#!/bin/bash

which podman > /dev/null && runner=podman
which container > /dev/null && runner=container
which docker > /dev/null && runner=docker

[ "$runner" = "" ] && { echo "None of pdoman, container or docker tool found, aborting" ; exit 1 ; }

$DEBUG $runner run --rm -it -v $(pwd):/current:ro $1
